name: ESLint check

on:
  push:
    branches: [ "main", "dev"]
  pull_request: 
    branches: [ "main"]

env:
  CI: true

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint
          npm install eslint-config-airbnb-base
          npm install eslint-plugin-import
          npm install eslint-plugin-functional
          npm install eslint-plugin-jsx-a11y
          npm install eslint-plugin-react
          npminstall  eslint-plugin-react-hooks

      - name: Run ESLint
        run: cd frontend && npx eslint .
        continue-on-error: true